{% set name = "argopt" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7045b95525ea7b8ce31964eb2ee247f92702e845258567db5f8e2469fe03689c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=3.7

test:
  imports:
    - argopt

about:
  home: https://pypi.python.org/pypi/tqdm
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENCE
  summary: doc to argparse driven by docopt

extra:
  recipe-maintainers:
    - casperdcl
    - jiangweiyao
