{% set name = "argopt" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55913a15099d4cecec5493e1b8976a90bf48a0ad3d174d42a44ba487ac385abf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.6
    - pip
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=2.6

test:
  imports:
    - argopt

about:
  home: https://pypi.python.org/pypi/tqdm
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENCE
  summary: doc to argparse driven by docopt

extra:
  recipe-maintainers:
    - casperdcl
    - jiangweiyao
